# Generated by Django 3.2.3 on 2021-05-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_restaurantes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantes',
            name='rating',
            field=models.TextField(),
        ),
    ]
