# Generated by Django 3.2.3 on 2021-05-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_restaurantes_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantes',
            name='lat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='restaurantes',
            name='lng',
            field=models.TextField(),
        ),
    ]
