# Generated by Django 3.2.3 on 2021-05-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210522_1922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurantes',
            new_name='Restaurante',
        ),
    ]
